#!/bin/bash

echo Beginning install process for DataProcessor dependencies...
echo
python3.7 -m pip install axographio
python3.7 -m pip install matplotlib
echo Going back to login directory, changing to flash drive...
echo
cd ~
cd Desktop/Axograph\ Processor\ Script/
ls -la
echo Starting DataProcessorv3Mac.py...
echo
python3 DataProcessorv3\ Mac.py

